version: '3.3'

services:
  # Development version of Next.js application with hot reloading
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://everleighAdmin:EverleighAdmin2685a57376c7f8ab@mongodb:27017/everleigh?authSource=admin
      - NEXTAUTH_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379
      - DISABLE_REDIS=false
      # TypeScript environment variables
      - TS_NODE_PROJECT=tsconfig.json
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - mongodb
      - redis
    networks:
      - everleigh-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  redis:
    image: redis:7-alpine
    restart: always
    hostname: redis
    expose:
      - 6379
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:6.0
    restart: always
    hostname: mongodb
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data: 