FROM node:18-alpine

WORKDIR /app

# Set environment variables
ENV NODE_ENV=production
ENV PORT=3001

# Copy the pre-built application
COPY .next ./.next
COPY public ./public
COPY node_modules ./node_modules
COPY package.json ./
COPY next.config.js ./

EXPOSE 3001

# Start the Next.js application
CMD ["npm", "run", "start"] 