version: '3.3'

services:
  # Next.js Application
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://everleighAdmin:EverleighAdmin2685a57376c7f8ab@mongodb:27017/everleigh?authSource=admin
      - NEXTAUTH_URL=http://localhost:3002
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    volumes:
      - ./public:/app/public
      - ./.env.local:/app/.env.local:ro
    depends_on:
      - mongodb
    networks:
      - everleigh-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:0.214.3
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=EverleighN8n
      - NODE_ENV=production
      - N8N_LOG_LEVEL=info
      - GENERIC_TIMEZONE=UTC
      - N8N_DIAGNOSTICS_ENABLED=false
    command: /bin/sh -c "sleep 5; n8n start"
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - everleigh-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "n8n"]
      interval: 30s
      timeout: 10s
      retries: 3

  # LiveKit Server
  livekit:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881/udp"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml
    networks:
      - everleigh-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=everleighAdmin
      - MONGO_INITDB_ROOT_PASSWORD=EverleighAdmin2685a57376c7f8ab
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - everleigh-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["--bind_ip_all", "--auth"]

networks:
  everleigh-network:
    driver: bridge

volumes:
  n8n-data:
    driver: local
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local 