version: '3.3'

services:
  redis:
    image: redis:7-alpine
    container_name: everleigh-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      --requirepass ${REDIS_PASSWORD:-everleighredis}
    networks:
      - everleigh-network

# Define persistent volumes
volumes:
  redis_data:

# Define shared network
networks:
  everleigh-network:
    driver: bridge 